### ISSUE TITLE
[Bug]: Crash Server 1.20.1 FORGE

### ISSUE THREAD

**Issue by Eriuis** [Toadstool-Studios/Creeper-Overhaul#157]
### Bug Description

When exploring the world the server crashes with a message: 

"creeperoverhaul:cave_creeper (tech.thatgravyboat.creeperoverhaul.common.entity.base.BaseCreeper)"

Btw, it also mentions the "Critters and Companions" mod but I'm not sure whether to open the report here or on the Critters and Companions wall, I'm sorry if I'm in the wrong place.

### How to Reproduce?

1-Join world
2-Explore the world
3-Random crash

### Expected Behavior

Play normally without the server crashing

### Version

creeperoverhaul-3.0.2-forge

### Mod Loader Version

1.20.1/47.3.0

### Mod Loader

Forge

### Logs or additional context

Crash report:
[crash-2024-10-03_14.00.39-server.txt](https://github.com/user-attachments/files/17249079/crash-2024-10-03_14.00.39-server.txt)

Log:
[latest.log](https://github.com/user-attachments/files/17249086/latest.log)

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by Minebrah** [comment]
I actually have the same problem. Funny enough I also found that the Critters and companions mod also was causing problems so I uninstalled it. This mod is also causing problems though so you're right, both mods are broken right now. 
Like OP said this mod is causing servers to crash on the latest creeperoverhaul-3.0.2-forge.jar

[05Oct2024 21:06:12.859] [Server thread/WARN] [com.performant.coremod.Performant/]: Adding large movement value! previous:(0.09072897155014419, -186.8837926786946, 0.08352241922540689) new:(0.09072897155014419, -589.2033680572372, 0.08352241922540689) to entity Ocean Creeper
java.lang.Exception: null
	at net.minecraft.world.entity.LivingEntity.m_20256_(LivingEntity.java:4034) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at tech.thatgravyboat.creeperoverhaul.common.entity.goals.WaterCreeperMoveControl.m_8126_(WaterCreeperMoveControl.java:30) ~[creeperoverhaul-3.0.2-forge.jar%231138!/:?]
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:772) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2548) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:536) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.world.entity.monster.Monster.m_8107_(Monster.java:42) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at tech.thatgravyboat.creeperoverhaul.common.entity.base.WaterCreeper.m_8107_(WaterCreeper.java:94) ~[creeperoverhaul-3.0.2-forge.jar%231138!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2298) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:337) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.world.entity.monster.Creeper.m_8119_(Creeper.java:161) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at tech.thatgravyboat.creeperoverhaul.common.entity.base.BaseCreeper.m_8119_(BaseCreeper.java:192) ~[creeperoverhaul-3.0.2-forge.jar%231138!/:?]
	at tech.thatgravyboat.creeperoverhaul.common.entity.custom.PufferfishCreeper.m_8119_(PufferfishCreeper.java:154) ~[creeperoverhaul-3.0.2-forge.jar%231138!/:?]
	at net.minecraft.server.level.ServerLevel.observable$track(ServerLevel.java:8169) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.server.level.ServerLevel.redirect$eld000$observable$onTickNonPassenger(ServerLevel.java:8185) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.server.level.ServerLevel.m_46653_(ServerLevel.java:12658) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[05Oct2024 21:06:12.910] [Server thread/WARN] [com.performant.coremod.Performant/]: Adding large movement value! previous:(0.09598639726329297, -0.0759000015258789, 0.08829614151322648) new:(0.09598639726329297, 526.7552944503336, 0.08829614151322648) to entity Ocean Creeper
java.lang.Exception: null
	at net.minecraft.world.entity.LivingEntity.m_20256_(LivingEntity.java:4034) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at tech.thatgravyboat.creeperoverhaul.common.entity.goals.WaterCreeperMoveControl.m_8126_(WaterCreeperMoveControl.java:30) ~[creeperoverhaul-3.0.2-forge.jar%231138!/:?]
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:772) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2548) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:536) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.world.entity.monster.Monster.m_8107_(Monster.java:42) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at tech.thatgravyboat.creeperoverhaul.common.entity.base.WaterCreeper.m_8107_(WaterCreeper.java:94) ~[creeperoverhaul-3.0.2-forge.jar%231138!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2298) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:337) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.world.entity.monster.Creeper.m_8119_(Creeper.java:161) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at tech.thatgravyboat.creeperoverhaul.common.entity.base.BaseCreeper.m_8119_(BaseCreeper.java:192) ~[creeperoverhaul-3.0.2-forge.jar%231138!/:?]
	at tech.thatgravyboat.creeperoverhaul.common.entity.custom.PufferfishCreeper.m_8119_(PufferfishCreeper.java:154) ~[creeperoverhaul-3.0.2-forge.jar%231138!/:?]
	at net.minecraft.server.level.ServerLevel.observable$track(ServerLevel.java:8169) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.server.level.ServerLevel.redirect$eld000$observable$onTickNonPassenger(ServerLevel.java:8185) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.server.level.ServerLevel.m_46653_(ServerLevel.java:12658) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%231760!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
